spring:
  datasource:
    username: root
    password: root123.
    url: jdbc:mysql://localhost:3306/emp?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.yhorm.pojo
  mapper-locations: classpath:mapper/*.xml